module.exports = Object.freeze({
  tickRate: 10,
  mapWidth: 1600,
  mapHeight: 900,
  startingResources: Object.freeze({ metal: 30, energy: 20, silicon: 10 }),
  spawnCost: Object.freeze({ metal: 10, energy: 5, silicon: 0 }),
  baseHp: 1000,
  botHp: 100,
  botSpeed: 80,
  maxBotsPerPlayer: 40,
  maxPlayers: 8,
  botDamage: 10,
  botAttackRange: 35,
  botAttackCooldown: 500,
  visionRange: 250,
  resourceAmount: 20,
  resourceCount: 40,
  resourceRespawnInterval: 5000,
  mineRange: 25,
  mineAmount: 2,
  unloadRange: 35,
  cargoCapacity: 10,
  communicationRange: 120,
  baseVisionRange: 250,
  baseCommunicationRange: 180,
  maxMessagesPerTick: 4,
  maxInboxMessages: 32,
  maxDamageEvents: 32,
  maxQueuedMessages: 4096,
  messageMaxBytes: 1024,
  scriptOperationLimit: 100,
  designPoints: 10,
  designDefaults: Object.freeze({ speed: 0, armor: 0, attack: 0, vision: 0, cargo: 0, communication: 0, cpu: 0, energy: 0 }),
  designScaling: Object.freeze({ speed: 20, armor: 20, attack: 3, vision: 60, cargo: 5, communication: 60, cpu: 40, energy: 15 }),
  designCostMetal: Object.freeze({ speed: 1, armor: 1, attack: 1, vision: 1, cargo: 1, communication: 1, cpu: 1, energy: 1 }),
  designCostEnergy: Object.freeze({ speed: 1, armor: 0, attack: 1, vision: 1, cargo: 0, communication: 0, cpu: 1, energy: 1 }),
  designCostSilicon: Object.freeze({ speed: 0, armor: 0, attack: 1, vision: 1, cargo: 0, communication: 1, cpu: 1, energy: 0 }),
  armorPerPoint: 1,
  minimumDamage: 1,
  botEnergy: 40,
  energyRegen: 1,
  baseEnergy: 100,
  baseEnergyRegen: 2,
  baseCpuBudget: 200,
  memoryMaxBytes: 4096,
  tagsMaxBytes: 1024,
  maxPrograms: 32,
  maxLastSeenEntries: 1000,
  cpuOperationCost: 1,
  apiCpuCosts: Object.freeze({ scan: 5, len: 1, send: 1, receive: 1, moveTo: 1, attack: 2, mine: 2, unload: 1, getCargo: 1, canSpawn: 1, spawn: 2, distance: 1, random: 1, getPosition: 1, getBase: 1, getHealth: 1, getResources: 1, getEnergy: 1, getBots: 1, count: 1, getTags: 1, setTag: 1 }),
  actionEnergyCosts: Object.freeze({ movement: 1, scan: 1, attack: 4, mine: 2, unload: 1, send: 2, spawn: 5 }),
})
